- name: Include variables
  include_vars: "{{ ansible_facts.os_family }}-{{ ansible_facts.distribution_major_version }}.yml"

- name: Register Red Hat subscription
  redhat_subscription:
    username: "{{ rhsm_username }}"
    password: "{{ rhsm_password }}"
    consumer_name: "{{ ansible_facts.hostname }}"
    state: present
    pool_ids: "{{ rhsm_pool_ids }}"
  when: ansible_facts.distribution == 'RedHat'

- name: Install packages
  yum:
    name: "{{ yum_packages }}"
    state: present

- name: Create user accounts and set password
  user:
    name: "{{ item.name }}"
    password: "{{ item.password | password_hash }}"
    state: present
  loop: "{{ packer_users }}"

# Fix slow DNS.
# https://github.com/mitchellh/vagrant/issues/1172
- name: Fix slow DNS
  lineinfile:
    dest: /etc/sysconfig/network
    regexp: '^RES_OPTIONS'
    line: 'RES_OPTIONS="single-request-reopen"'
    state: present
  register: slow_dns_fix
  tags:
    - notest

- name: Restart network service
  service:
    name: network
    state: restarted
  when: slow_dns_fix is changed
  tags:
    - notest

- name: Configure passwordless sudo without TTY
  lineinfile:
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    dest: /etc/sudoers
    validate: visudo -cf %s
  loop:
    - regexp: "^.*requiretty"
      line: "#Defaults requiretty"

    - regexp: "^vagrant.*NOPASSWD:.*ALL"
      line: "vagrant        ALL=(ALL)       NOPASSWD: ALL"

- name: Configure SSH
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  loop:
    - regexp: "^#?UseDNS"
      line: "UseDNS no"

    - regexp: "^#?GSSAPIAuthentication"
      line: "GSSAPIAuthentication no"
  tags:
    - notest

- name: Add Vagrant SSH key
  authorized_key:
    user: vagrant
    key: https://github.com/mitchellh/vagrant/raw/master/keys/vagrant.pub

- name: Remove udev rules for network devices
  file:
    dest: /etc/udev/rules.d/70-persistent-net.rules
    state: absent

- name: List network config files
  shell: ls /etc/sysconfig/network-scripts/ifcfg-*
  register: network_config_files
  changed_when: no

- name: Remove device specific network settings
  lineinfile:
    dest: "{{ item[0] }}"
    regexp: "{{ item[1] }}"
    state: absent
  with_nested:
    - "{{ network_config_files.stdout_lines }}"
    - ["^HWADDR", "^UUID" ]

- name: Configure services
  service:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
    enabled: "{{ item.enabled }}"
  loop: "{{ packer_services | union(packer_services_unique) }}"
  when: ansible_facts.distribution_major_version is version_compare(item.version, ">=")

- name: Install all updates
  yum:
    name: "*"
    state: latest
  tags:
    - notest

- name: Check for Virtualbox
  stat:
    path: /home/vagrant/.vbox_version
  register: virtualbox_check

- import_tasks: virtualbox.yml
  when: virtualbox_check.stat.exists

- name: Deregister Red Hat subscription
  redhat_subscription:
    username: "{{ rhsm_username }}"
    password: "{{ rhsm_password }}"
    state: absent
  when: ansible_facts.distribution == 'RedHat'
